name: "Development SFPI"

on:
  workflow_dispatch:
    inputs:
      all:
        required: true
        description: All targets
        type: boolean
        default: false
      full:
        required: true
        description: Complete build
        type: boolean
        default: false

run-name: Development build SFPI ${{github.ref}}
jobs:
  dev:
    uses: ./.github/workflows/release-sfpi.yaml
    with:
      full: ${{inputs.full}}
      all: ${{inputs.all}}
      id_prefix: 'dev-'
